### ISSUE TITLE
Support for Consul 1.4 ACLs?

### ISSUE THREAD

**Issue by vide** [ashald/terraform-provider-consulacl#3]
Hello, do you plan supporting the new consul 1.4 ACLs? The token it creates right now is "legacy" and it doesn't work with the new policies/tokens workflow.

**Comment by ketzacoatl** [comment]
FWIW, given the scope of what changed in 1.4.. it is likely to be a relatively straight-forward update, but not trivial.

**Comment by ashald** [comment]
It's available in the official provider https://www.terraform.io/docs/providers/consul/r/acl_token.html
